// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartitionBrokerRole int32

const (
	PartitionBrokerRole_LEADER   PartitionBrokerRole = 0
	PartitionBrokerRole_FOLLOWER PartitionBrokerRole = 1
	PartitionBrokerRole_INACTIVE PartitionBrokerRole = 2
)

// Enum value maps for PartitionBrokerRole.
var (
	PartitionBrokerRole_name = map[int32]string{
		0: "LEADER",
		1: "FOLLOWER",
		2: "INACTIVE",
	}
	PartitionBrokerRole_value = map[string]int32{
		"LEADER":   0,
		"FOLLOWER": 1,
		"INACTIVE": 2,
	}
)

func (x PartitionBrokerRole) Enum() *PartitionBrokerRole {
	p := new(PartitionBrokerRole)
	*p = x
	return p
}

func (x PartitionBrokerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartitionBrokerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[0].Descriptor()
}

func (PartitionBrokerRole) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[0]
}

func (x PartitionBrokerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartitionBrokerRole.Descriptor instead.
func (PartitionBrokerRole) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

type PartitionBrokerHealth int32

const (
	PartitionBrokerHealth_HEALTHY   PartitionBrokerHealth = 0
	PartitionBrokerHealth_UNHEALTHY PartitionBrokerHealth = 1
	PartitionBrokerHealth_DEAD      PartitionBrokerHealth = 2
)

// Enum value maps for PartitionBrokerHealth.
var (
	PartitionBrokerHealth_name = map[int32]string{
		0: "HEALTHY",
		1: "UNHEALTHY",
		2: "DEAD",
	}
	PartitionBrokerHealth_value = map[string]int32{
		"HEALTHY":   0,
		"UNHEALTHY": 1,
		"DEAD":      2,
	}
)

func (x PartitionBrokerHealth) Enum() *PartitionBrokerHealth {
	p := new(PartitionBrokerHealth)
	*p = x
	return p
}

func (x PartitionBrokerHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartitionBrokerHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[1].Descriptor()
}

func (PartitionBrokerHealth) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[1]
}

func (x PartitionBrokerHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartitionBrokerHealth.Descriptor instead.
func (PartitionBrokerHealth) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

type TopologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRequest) Reset() {
	*x = TopologyRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequest) ProtoMessage() {}

func (x *TopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequest.ProtoReflect.Descriptor instead.
func (*TopologyRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

type TopologyResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Brokers           []*BrokerInfo          `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	ClusterSize       int32                  `protobuf:"varint,2,opt,name=clusterSize,proto3" json:"clusterSize,omitempty"`
	PartitionsCount   int32                  `protobuf:"varint,3,opt,name=partitionsCount,proto3" json:"partitionsCount,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,4,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	GatewayVersion    string                 `protobuf:"bytes,5,opt,name=gatewayVersion,proto3" json:"gatewayVersion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TopologyResponse) Reset() {
	*x = TopologyResponse{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyResponse) ProtoMessage() {}

func (x *TopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyResponse.ProtoReflect.Descriptor instead.
func (*TopologyResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *TopologyResponse) GetBrokers() []*BrokerInfo {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *TopologyResponse) GetClusterSize() int32 {
	if x != nil {
		return x.ClusterSize
	}
	return 0
}

func (x *TopologyResponse) GetPartitionsCount() int32 {
	if x != nil {
		return x.PartitionsCount
	}
	return 0
}

func (x *TopologyResponse) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *TopologyResponse) GetGatewayVersion() string {
	if x != nil {
		return x.GatewayVersion
	}
	return ""
}

type BrokerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Partitions    []*Partition           `protobuf:"bytes,4,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfo) Reset() {
	*x = BrokerInfo{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfo) ProtoMessage() {}

func (x *BrokerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfo.ProtoReflect.Descriptor instead.
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *BrokerInfo) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *BrokerInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BrokerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BrokerInfo) GetPartitions() []*Partition {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *BrokerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Partition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Role          PartitionBrokerRole    `protobuf:"varint,2,opt,name=role,proto3,enum=gateway_protocol.PartitionBrokerRole" json:"role,omitempty"`
	Health        PartitionBrokerHealth  `protobuf:"varint,3,opt,name=health,proto3,enum=gateway_protocol.PartitionBrokerHealth" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Partition) Reset() {
	*x = Partition{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *Partition) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *Partition) GetRole() PartitionBrokerRole {
	if x != nil {
		return x.Role
	}
	return PartitionBrokerRole_LEADER
}

func (x *Partition) GetHealth() PartitionBrokerHealth {
	if x != nil {
		return x.Health
	}
	return PartitionBrokerHealth_HEALTHY
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DeployResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResourceRequest) Reset() {
	*x = DeployResourceRequest{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResourceRequest) ProtoMessage() {}

func (x *DeployResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResourceRequest.ProtoReflect.Descriptor instead.
func (*DeployResourceRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *DeployResourceRequest) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DeployResourceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeployResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Deployments   []*Deployment          `protobuf:"bytes,2,rep,name=deployments,proto3" json:"deployments,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResourceResponse) Reset() {
	*x = DeployResourceResponse{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResourceResponse) ProtoMessage() {}

func (x *DeployResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResourceResponse.ProtoReflect.Descriptor instead.
func (*DeployResourceResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *DeployResourceResponse) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *DeployResourceResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *DeployResourceResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type Deployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Metadata:
	//
	//	*Deployment_Process
	//	*Deployment_Decision
	//	*Deployment_DecisionRequirements
	//	*Deployment_Form
	Metadata      isDeployment_Metadata `protobuf_oneof:"Metadata"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *Deployment) GetMetadata() isDeployment_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Deployment) GetProcess() *ProcessMetadata {
	if x != nil {
		if x, ok := x.Metadata.(*Deployment_Process); ok {
			return x.Process
		}
	}
	return nil
}

func (x *Deployment) GetDecision() *DecisionMetadata {
	if x != nil {
		if x, ok := x.Metadata.(*Deployment_Decision); ok {
			return x.Decision
		}
	}
	return nil
}

func (x *Deployment) GetDecisionRequirements() *DecisionRequirementsMetadata {
	if x != nil {
		if x, ok := x.Metadata.(*Deployment_DecisionRequirements); ok {
			return x.DecisionRequirements
		}
	}
	return nil
}

func (x *Deployment) GetForm() *FormMetadata {
	if x != nil {
		if x, ok := x.Metadata.(*Deployment_Form); ok {
			return x.Form
		}
	}
	return nil
}

type isDeployment_Metadata interface {
	isDeployment_Metadata()
}

type Deployment_Process struct {
	Process *ProcessMetadata `protobuf:"bytes,1,opt,name=process,proto3,oneof"`
}

type Deployment_Decision struct {
	Decision *DecisionMetadata `protobuf:"bytes,2,opt,name=decision,proto3,oneof"`
}

type Deployment_DecisionRequirements struct {
	DecisionRequirements *DecisionRequirementsMetadata `protobuf:"bytes,3,opt,name=decisionRequirements,proto3,oneof"`
}

type Deployment_Form struct {
	Form *FormMetadata `protobuf:"bytes,4,opt,name=form,proto3,oneof"`
}

func (*Deployment_Process) isDeployment_Metadata() {}

func (*Deployment_Decision) isDeployment_Metadata() {}

func (*Deployment_DecisionRequirements) isDeployment_Metadata() {}

func (*Deployment_Form) isDeployment_Metadata() {}

type ProcessMetadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BpmnProcessId        string                 `protobuf:"bytes,1,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ProcessDefinitionKey int64                  `protobuf:"varint,3,opt,name=processDefinitionKey,proto3" json:"processDefinitionKey,omitempty"`
	ResourceName         string                 `protobuf:"bytes,4,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	TenantId             string                 `protobuf:"bytes,5,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProcessMetadata) Reset() {
	*x = ProcessMetadata{}
	mi := &file_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetadata) ProtoMessage() {}

func (x *ProcessMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetadata.ProtoReflect.Descriptor instead.
func (*ProcessMetadata) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessMetadata) GetBpmnProcessId() string {
	if x != nil {
		return x.BpmnProcessId
	}
	return ""
}

func (x *ProcessMetadata) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProcessMetadata) GetProcessDefinitionKey() int64 {
	if x != nil {
		return x.ProcessDefinitionKey
	}
	return 0
}

func (x *ProcessMetadata) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ProcessMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DecisionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionMetadata) Reset() {
	*x = DecisionMetadata{}
	mi := &file_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionMetadata) ProtoMessage() {}

func (x *DecisionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionMetadata.ProtoReflect.Descriptor instead.
func (*DecisionMetadata) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{9}
}

type DecisionRequirementsMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequirementsMetadata) Reset() {
	*x = DecisionRequirementsMetadata{}
	mi := &file_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequirementsMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequirementsMetadata) ProtoMessage() {}

func (x *DecisionRequirementsMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequirementsMetadata.ProtoReflect.Descriptor instead.
func (*DecisionRequirementsMetadata) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{10}
}

type FormMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormMetadata) Reset() {
	*x = FormMetadata{}
	mi := &file_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormMetadata) ProtoMessage() {}

func (x *FormMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormMetadata.ProtoReflect.Descriptor instead.
func (*FormMetadata) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{11}
}

type CreateProcessInstanceRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProcessDefinitionKey int64                  `protobuf:"varint,1,opt,name=processDefinitionKey,proto3" json:"processDefinitionKey,omitempty"`
	BpmnProcessId        string                 `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Variables            string                 `protobuf:"bytes,4,opt,name=variables,proto3" json:"variables,omitempty"`
	TenantId             string                 `protobuf:"bytes,6,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateProcessInstanceRequest) Reset() {
	*x = CreateProcessInstanceRequest{}
	mi := &file_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessInstanceRequest) ProtoMessage() {}

func (x *CreateProcessInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateProcessInstanceRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *CreateProcessInstanceRequest) GetProcessDefinitionKey() int64 {
	if x != nil {
		return x.ProcessDefinitionKey
	}
	return 0
}

func (x *CreateProcessInstanceRequest) GetBpmnProcessId() string {
	if x != nil {
		return x.BpmnProcessId
	}
	return ""
}

func (x *CreateProcessInstanceRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateProcessInstanceRequest) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

func (x *CreateProcessInstanceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CreateProcessInstanceResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProcessDefinitionKey int64                  `protobuf:"varint,1,opt,name=processDefinitionKey,proto3" json:"processDefinitionKey,omitempty"`
	BpmnProcessId        string                 `protobuf:"bytes,2,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	Version              int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	ProcessInstanceKey   int64                  `protobuf:"varint,4,opt,name=processInstanceKey,proto3" json:"processInstanceKey,omitempty"`
	TenantId             string                 `protobuf:"bytes,5,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateProcessInstanceResponse) Reset() {
	*x = CreateProcessInstanceResponse{}
	mi := &file_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProcessInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessInstanceResponse) ProtoMessage() {}

func (x *CreateProcessInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateProcessInstanceResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProcessInstanceResponse) GetProcessDefinitionKey() int64 {
	if x != nil {
		return x.ProcessDefinitionKey
	}
	return 0
}

func (x *CreateProcessInstanceResponse) GetBpmnProcessId() string {
	if x != nil {
		return x.BpmnProcessId
	}
	return ""
}

func (x *CreateProcessInstanceResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CreateProcessInstanceResponse) GetProcessInstanceKey() int64 {
	if x != nil {
		return x.ProcessInstanceKey
	}
	return 0
}

func (x *CreateProcessInstanceResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ActivateJobsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Worker            string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	Timeout           int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxJobsToActivate int32                  `protobuf:"varint,4,opt,name=maxJobsToActivate,proto3" json:"maxJobsToActivate,omitempty"`
	FetchVariable     []string               `protobuf:"bytes,5,rep,name=fetchVariable,proto3" json:"fetchVariable,omitempty"`
	RequestTimeout    int64                  `protobuf:"varint,6,opt,name=requestTimeout,proto3" json:"requestTimeout,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActivateJobsRequest) Reset() {
	*x = ActivateJobsRequest{}
	mi := &file_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateJobsRequest) ProtoMessage() {}

func (x *ActivateJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateJobsRequest.ProtoReflect.Descriptor instead.
func (*ActivateJobsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *ActivateJobsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActivateJobsRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *ActivateJobsRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ActivateJobsRequest) GetMaxJobsToActivate() int32 {
	if x != nil {
		return x.MaxJobsToActivate
	}
	return 0
}

func (x *ActivateJobsRequest) GetFetchVariable() []string {
	if x != nil {
		return x.FetchVariable
	}
	return nil
}

func (x *ActivateJobsRequest) GetRequestTimeout() int64 {
	if x != nil {
		return x.RequestTimeout
	}
	return 0
}

type ActivateJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*ActivatedJob        `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateJobsResponse) Reset() {
	*x = ActivateJobsResponse{}
	mi := &file_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateJobsResponse) ProtoMessage() {}

func (x *ActivateJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateJobsResponse.ProtoReflect.Descriptor instead.
func (*ActivateJobsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *ActivateJobsResponse) GetJobs() []*ActivatedJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ActivatedJob struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Key                      int64                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Type                     string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ProcessInstanceKey       int64                  `protobuf:"varint,3,opt,name=processInstanceKey,proto3" json:"processInstanceKey,omitempty"`
	BpmnProcessId            string                 `protobuf:"bytes,4,opt,name=bpmnProcessId,proto3" json:"bpmnProcessId,omitempty"`
	ProcessDefinitionVersion int32                  `protobuf:"varint,5,opt,name=processDefinitionVersion,proto3" json:"processDefinitionVersion,omitempty"`
	ProcessDefinitionKey     int64                  `protobuf:"varint,6,opt,name=processDefinitionKey,proto3" json:"processDefinitionKey,omitempty"`
	ElementId                string                 `protobuf:"bytes,7,opt,name=elementId,proto3" json:"elementId,omitempty"`
	ElementInstanceKey       int64                  `protobuf:"varint,8,opt,name=elementInstanceKey,proto3" json:"elementInstanceKey,omitempty"`
	CustomHeaders            string                 `protobuf:"bytes,9,opt,name=customHeaders,proto3" json:"customHeaders,omitempty"`
	Worker                   string                 `protobuf:"bytes,10,opt,name=worker,proto3" json:"worker,omitempty"`
	Retries                  int32                  `protobuf:"varint,11,opt,name=retries,proto3" json:"retries,omitempty"`
	Deadline                 int64                  `protobuf:"varint,12,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Variables                string                 `protobuf:"bytes,13,opt,name=variables,proto3" json:"variables,omitempty"`
	TenantId                 string                 `protobuf:"bytes,14,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ActivatedJob) Reset() {
	*x = ActivatedJob{}
	mi := &file_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivatedJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivatedJob) ProtoMessage() {}

func (x *ActivatedJob) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivatedJob.ProtoReflect.Descriptor instead.
func (*ActivatedJob) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *ActivatedJob) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ActivatedJob) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActivatedJob) GetProcessInstanceKey() int64 {
	if x != nil {
		return x.ProcessInstanceKey
	}
	return 0
}

func (x *ActivatedJob) GetBpmnProcessId() string {
	if x != nil {
		return x.BpmnProcessId
	}
	return ""
}

func (x *ActivatedJob) GetProcessDefinitionVersion() int32 {
	if x != nil {
		return x.ProcessDefinitionVersion
	}
	return 0
}

func (x *ActivatedJob) GetProcessDefinitionKey() int64 {
	if x != nil {
		return x.ProcessDefinitionKey
	}
	return 0
}

func (x *ActivatedJob) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *ActivatedJob) GetElementInstanceKey() int64 {
	if x != nil {
		return x.ElementInstanceKey
	}
	return 0
}

func (x *ActivatedJob) GetCustomHeaders() string {
	if x != nil {
		return x.CustomHeaders
	}
	return ""
}

func (x *ActivatedJob) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *ActivatedJob) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *ActivatedJob) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *ActivatedJob) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

func (x *ActivatedJob) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CompleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobKey        int64                  `protobuf:"varint,1,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	Variables     string                 `protobuf:"bytes,2,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobRequest) Reset() {
	*x = CompleteJobRequest{}
	mi := &file_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobRequest) ProtoMessage() {}

func (x *CompleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *CompleteJobRequest) GetJobKey() int64 {
	if x != nil {
		return x.JobKey
	}
	return 0
}

func (x *CompleteJobRequest) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

type CompleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobResponse) Reset() {
	*x = CompleteJobResponse{}
	mi := &file_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobResponse) ProtoMessage() {}

func (x *CompleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobResponse.ProtoReflect.Descriptor instead.
func (*CompleteJobResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{18}
}

type FailJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobKey        int64                  `protobuf:"varint,1,opt,name=jobKey,proto3" json:"jobKey,omitempty"`
	Retries       int32                  `protobuf:"varint,2,opt,name=retries,proto3" json:"retries,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	RetryBackOff  int64                  `protobuf:"varint,4,opt,name=retryBackOff,proto3" json:"retryBackOff,omitempty"`
	Variables     string                 `protobuf:"bytes,5,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailJobRequest) Reset() {
	*x = FailJobRequest{}
	mi := &file_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailJobRequest) ProtoMessage() {}

func (x *FailJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailJobRequest.ProtoReflect.Descriptor instead.
func (*FailJobRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *FailJobRequest) GetJobKey() int64 {
	if x != nil {
		return x.JobKey
	}
	return 0
}

func (x *FailJobRequest) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *FailJobRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FailJobRequest) GetRetryBackOff() int64 {
	if x != nil {
		return x.RetryBackOff
	}
	return 0
}

func (x *FailJobRequest) GetVariables() string {
	if x != nil {
		return x.Variables
	}
	return ""
}

type FailJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailJobResponse) Reset() {
	*x = FailJobResponse{}
	mi := &file_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailJobResponse) ProtoMessage() {}

func (x *FailJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailJobResponse.ProtoReflect.Descriptor instead.
func (*FailJobResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{20}
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x10gateway_protocol\"\x11\n" +
	"\x0fTopologyRequest\"\xec\x01\n" +
	"\x10TopologyResponse\x126\n" +
	"\abrokers\x18\x01 \x03(\v2\x1c.gateway_protocol.BrokerInfoR\abrokers\x12 \n" +
	"\vclusterSize\x18\x02 \x01(\x05R\vclusterSize\x12(\n" +
	"\x0fpartitionsCount\x18\x03 \x01(\x05R\x0fpartitionsCount\x12,\n" +
	"\x11replicationFactor\x18\x04 \x01(\x05R\x11replicationFactor\x12&\n" +
	"\x0egatewayVersion\x18\x05 \x01(\tR\x0egatewayVersion\"\xa3\x01\n" +
	"\n" +
	"BrokerInfo\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x05R\x06nodeId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12;\n" +
	"\n" +
	"partitions\x18\x04 \x03(\v2\x1b.gateway_protocol.PartitionR\n" +
	"partitions\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\xa9\x01\n" +
	"\tPartition\x12 \n" +
	"\vpartitionId\x18\x01 \x01(\x05R\vpartitionId\x129\n" +
	"\x04role\x18\x02 \x01(\x0e2%.gateway_protocol.PartitionBrokerRoleR\x04role\x12?\n" +
	"\x06health\x18\x03 \x01(\x0e2'.gateway_protocol.PartitionBrokerHealthR\x06health\"8\n" +
	"\bResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"m\n" +
	"\x15DeployResourceRequest\x128\n" +
	"\tresources\x18\x01 \x03(\v2\x1a.gateway_protocol.ResourceR\tresources\x12\x1a\n" +
	"\btenantId\x18\x02 \x01(\tR\btenantId\"\x86\x01\n" +
	"\x16DeployResourceResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12>\n" +
	"\vdeployments\x18\x02 \x03(\v2\x1c.gateway_protocol.DeploymentR\vdeployments\x12\x1a\n" +
	"\btenantId\x18\x03 \x01(\tR\btenantId\"\xb5\x02\n" +
	"\n" +
	"Deployment\x12=\n" +
	"\aprocess\x18\x01 \x01(\v2!.gateway_protocol.ProcessMetadataH\x00R\aprocess\x12@\n" +
	"\bdecision\x18\x02 \x01(\v2\".gateway_protocol.DecisionMetadataH\x00R\bdecision\x12d\n" +
	"\x14decisionRequirements\x18\x03 \x01(\v2..gateway_protocol.DecisionRequirementsMetadataH\x00R\x14decisionRequirements\x124\n" +
	"\x04form\x18\x04 \x01(\v2\x1e.gateway_protocol.FormMetadataH\x00R\x04formB\n" +
	"\n" +
	"\bMetadata\"\xc5\x01\n" +
	"\x0fProcessMetadata\x12$\n" +
	"\rbpmnProcessId\x18\x01 \x01(\tR\rbpmnProcessId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x122\n" +
	"\x14processDefinitionKey\x18\x03 \x01(\x03R\x14processDefinitionKey\x12\"\n" +
	"\fresourceName\x18\x04 \x01(\tR\fresourceName\x12\x1a\n" +
	"\btenantId\x18\x05 \x01(\tR\btenantId\"\x12\n" +
	"\x10DecisionMetadata\"\x1e\n" +
	"\x1cDecisionRequirementsMetadata\"\x0e\n" +
	"\fFormMetadata\"\xcc\x01\n" +
	"\x1cCreateProcessInstanceRequest\x122\n" +
	"\x14processDefinitionKey\x18\x01 \x01(\x03R\x14processDefinitionKey\x12$\n" +
	"\rbpmnProcessId\x18\x02 \x01(\tR\rbpmnProcessId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x1c\n" +
	"\tvariables\x18\x04 \x01(\tR\tvariables\x12\x1a\n" +
	"\btenantId\x18\x06 \x01(\tR\btenantId\"\xdf\x01\n" +
	"\x1dCreateProcessInstanceResponse\x122\n" +
	"\x14processDefinitionKey\x18\x01 \x01(\x03R\x14processDefinitionKey\x12$\n" +
	"\rbpmnProcessId\x18\x02 \x01(\tR\rbpmnProcessId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12.\n" +
	"\x12processInstanceKey\x18\x04 \x01(\x03R\x12processInstanceKey\x12\x1a\n" +
	"\btenantId\x18\x05 \x01(\tR\btenantId\"\xd7\x01\n" +
	"\x13ActivateJobsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12,\n" +
	"\x11maxJobsToActivate\x18\x04 \x01(\x05R\x11maxJobsToActivate\x12$\n" +
	"\rfetchVariable\x18\x05 \x03(\tR\rfetchVariable\x12&\n" +
	"\x0erequestTimeout\x18\x06 \x01(\x03R\x0erequestTimeout\"J\n" +
	"\x14ActivateJobsResponse\x122\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1e.gateway_protocol.ActivatedJobR\x04jobs\"\xf6\x03\n" +
	"\fActivatedJob\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12.\n" +
	"\x12processInstanceKey\x18\x03 \x01(\x03R\x12processInstanceKey\x12$\n" +
	"\rbpmnProcessId\x18\x04 \x01(\tR\rbpmnProcessId\x12:\n" +
	"\x18processDefinitionVersion\x18\x05 \x01(\x05R\x18processDefinitionVersion\x122\n" +
	"\x14processDefinitionKey\x18\x06 \x01(\x03R\x14processDefinitionKey\x12\x1c\n" +
	"\telementId\x18\a \x01(\tR\telementId\x12.\n" +
	"\x12elementInstanceKey\x18\b \x01(\x03R\x12elementInstanceKey\x12$\n" +
	"\rcustomHeaders\x18\t \x01(\tR\rcustomHeaders\x12\x16\n" +
	"\x06worker\x18\n" +
	" \x01(\tR\x06worker\x12\x18\n" +
	"\aretries\x18\v \x01(\x05R\aretries\x12\x1a\n" +
	"\bdeadline\x18\f \x01(\x03R\bdeadline\x12\x1c\n" +
	"\tvariables\x18\r \x01(\tR\tvariables\x12\x1a\n" +
	"\btenantId\x18\x0e \x01(\tR\btenantId\"J\n" +
	"\x12CompleteJobRequest\x12\x16\n" +
	"\x06jobKey\x18\x01 \x01(\x03R\x06jobKey\x12\x1c\n" +
	"\tvariables\x18\x02 \x01(\tR\tvariables\"\x15\n" +
	"\x13CompleteJobResponse\"\xa8\x01\n" +
	"\x0eFailJobRequest\x12\x16\n" +
	"\x06jobKey\x18\x01 \x01(\x03R\x06jobKey\x12\x18\n" +
	"\aretries\x18\x02 \x01(\x05R\aretries\x12\"\n" +
	"\ferrorMessage\x18\x03 \x01(\tR\ferrorMessage\x12\"\n" +
	"\fretryBackOff\x18\x04 \x01(\x03R\fretryBackOff\x12\x1c\n" +
	"\tvariables\x18\x05 \x01(\tR\tvariables\"\x11\n" +
	"\x0fFailJobResponse*=\n" +
	"\x13PartitionBrokerRole\x12\n" +
	"\n" +
	"\x06LEADER\x10\x00\x12\f\n" +
	"\bFOLLOWER\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02*=\n" +
	"\x15PartitionBrokerHealth\x12\v\n" +
	"\aHEALTHY\x10\x00\x12\r\n" +
	"\tUNHEALTHY\x10\x01\x12\b\n" +
	"\x04DEAD\x10\x022\xc8\x04\n" +
	"\aGateway\x12Q\n" +
	"\bTopology\x12!.gateway_protocol.TopologyRequest\x1a\".gateway_protocol.TopologyResponse\x12c\n" +
	"\x0eDeployResource\x12'.gateway_protocol.DeployResourceRequest\x1a(.gateway_protocol.DeployResourceResponse\x12x\n" +
	"\x15CreateProcessInstance\x12..gateway_protocol.CreateProcessInstanceRequest\x1a/.gateway_protocol.CreateProcessInstanceResponse\x12_\n" +
	"\fActivateJobs\x12%.gateway_protocol.ActivateJobsRequest\x1a&.gateway_protocol.ActivateJobsResponse0\x01\x12Z\n" +
	"\vCompleteJob\x12$.gateway_protocol.CompleteJobRequest\x1a%.gateway_protocol.CompleteJobResponse\x12N\n" +
	"\aFailJob\x12 .gateway_protocol.FailJobRequest\x1a!.gateway_protocol.FailJobResponseB5Z3github.com/jeremielodi/goflow/internal/zeebegrpc/pbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_gateway_proto_goTypes = []any{
	(PartitionBrokerRole)(0),              // 0: gateway_protocol.PartitionBrokerRole
	(PartitionBrokerHealth)(0),            // 1: gateway_protocol.PartitionBrokerHealth
	(*TopologyRequest)(nil),               // 2: gateway_protocol.TopologyRequest
	(*TopologyResponse)(nil),              // 3: gateway_protocol.TopologyResponse
	(*BrokerInfo)(nil),                    // 4: gateway_protocol.BrokerInfo
	(*Partition)(nil),                     // 5: gateway_protocol.Partition
	(*Resource)(nil),                      // 6: gateway_protocol.Resource
	(*DeployResourceRequest)(nil),         // 7: gateway_protocol.DeployResourceRequest
	(*DeployResourceResponse)(nil),        // 8: gateway_protocol.DeployResourceResponse
	(*Deployment)(nil),                    // 9: gateway_protocol.Deployment
	(*ProcessMetadata)(nil),               // 10: gateway_protocol.ProcessMetadata
	(*DecisionMetadata)(nil),              // 11: gateway_protocol.DecisionMetadata
	(*DecisionRequirementsMetadata)(nil),  // 12: gateway_protocol.DecisionRequirementsMetadata
	(*FormMetadata)(nil),                  // 13: gateway_protocol.FormMetadata
	(*CreateProcessInstanceRequest)(nil),  // 14: gateway_protocol.CreateProcessInstanceRequest
	(*CreateProcessInstanceResponse)(nil), // 15: gateway_protocol.CreateProcessInstanceResponse
	(*ActivateJobsRequest)(nil),           // 16: gateway_protocol.ActivateJobsRequest
	(*ActivateJobsResponse)(nil),          // 17: gateway_protocol.ActivateJobsResponse
	(*ActivatedJob)(nil),                  // 18: gateway_protocol.ActivatedJob
	(*CompleteJobRequest)(nil),            // 19: gateway_protocol.CompleteJobRequest
	(*CompleteJobResponse)(nil),           // 20: gateway_protocol.CompleteJobResponse
	(*FailJobRequest)(nil),                // 21: gateway_protocol.FailJobRequest
	(*FailJobResponse)(nil),               // 22: gateway_protocol.FailJobResponse
}
var file_gateway_proto_depIdxs = []int32{
	4,  // 0: gateway_protocol.TopologyResponse.brokers:type_name -> gateway_protocol.BrokerInfo
	5,  // 1: gateway_protocol.BrokerInfo.partitions:type_name -> gateway_protocol.Partition
	0,  // 2: gateway_protocol.Partition.role:type_name -> gateway_protocol.PartitionBrokerRole
	1,  // 3: gateway_protocol.Partition.health:type_name -> gateway_protocol.PartitionBrokerHealth
	6,  // 4: gateway_protocol.DeployResourceRequest.resources:type_name -> gateway_protocol.Resource
	9,  // 5: gateway_protocol.DeployResourceResponse.deployments:type_name -> gateway_protocol.Deployment
	10, // 6: gateway_protocol.Deployment.process:type_name -> gateway_protocol.ProcessMetadata
	11, // 7: gateway_protocol.Deployment.decision:type_name -> gateway_protocol.DecisionMetadata
	12, // 8: gateway_protocol.Deployment.decisionRequirements:type_name -> gateway_protocol.DecisionRequirementsMetadata
	13, // 9: gateway_protocol.Deployment.form:type_name -> gateway_protocol.FormMetadata
	18, // 10: gateway_protocol.ActivateJobsResponse.jobs:type_name -> gateway_protocol.ActivatedJob
	2,  // 11: gateway_protocol.Gateway.Topology:input_type -> gateway_protocol.TopologyRequest
	7,  // 12: gateway_protocol.Gateway.DeployResource:input_type -> gateway_protocol.DeployResourceRequest
	14, // 13: gateway_protocol.Gateway.CreateProcessInstance:input_type -> gateway_protocol.CreateProcessInstanceRequest
	16, // 14: gateway_protocol.Gateway.ActivateJobs:input_type -> gateway_protocol.ActivateJobsRequest
	19, // 15: gateway_protocol.Gateway.CompleteJob:input_type -> gateway_protocol.CompleteJobRequest
	21, // 16: gateway_protocol.Gateway.FailJob:input_type -> gateway_protocol.FailJobRequest
	3,  // 17: gateway_protocol.Gateway.Topology:output_type -> gateway_protocol.TopologyResponse
	8,  // 18: gateway_protocol.Gateway.DeployResource:output_type -> gateway_protocol.DeployResourceResponse
	15, // 19: gateway_protocol.Gateway.CreateProcessInstance:output_type -> gateway_protocol.CreateProcessInstanceResponse
	17, // 20: gateway_protocol.Gateway.ActivateJobs:output_type -> gateway_protocol.ActivateJobsResponse
	20, // 21: gateway_protocol.Gateway.CompleteJob:output_type -> gateway_protocol.CompleteJobResponse
	22, // 22: gateway_protocol.Gateway.FailJob:output_type -> gateway_protocol.FailJobResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_gateway_proto_msgTypes[7].OneofWrappers = []any{
		(*Deployment_Process)(nil),
		(*Deployment_Decision)(nil),
		(*Deployment_DecisionRequirements)(nil),
		(*Deployment_Form)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
